# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master


jobs:
  - job: install_nix
    strategy:
      matrix:
        ubuntu:
          imageName: 'ubuntu-16.04'
        mac:
          imageName: 'macos-10.13'
    pool:
      vmImage: $(imageName)
    steps:
      - template: ci/install-rust.yml
    displayName: Install (not Windows)

  - job: install_windows
    strategy:
      matrix:
        windows:
          imageName: 'vs2017-win2016'
    pool:
      vmImage: $(imageName)
    steps:
      - template: ci/install-rust.yml
    displayName: Install (Windows)

  - job: formatting
    strategy:
      matrix:
        ubuntu:
          imageName: 'ubuntu-16.04'
    steps:
      - template: ci/check-formatting.yml
    dependsOn: install_nix
    displayName: Check Formatting

  - job: test_nix
    strategy:
      matrix:
        ubuntu:
          imageName: 'ubuntu-16.04'
        mac:
          imageName: 'macos-10.13'
    steps:
      - template: ci/run-tests.yml
    dependsOn: install_nix
  
  - job: test_windows
    strategy:
      matrix:
        windows:
          imageName: 'vs2017-win2016'
    steps:
      - template: ci/run-tests.yml
    dependsOn: install_windows
