# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master


jobs:
  - job: Install
    strategy:
      matrix:
        ubuntu:
          imageName: 'ubuntu-16.04'
        mac:
          imageName: 'macos-10.13'
        windows:
          imageName: 'vs2017-win2016'
    pool:
      vmImage: $(imageName)
    steps:
      - template: ci/install-rust.yml
      - template: ci/test.yml
      - template: ci/formatting.yml

  - job: Formatting
    strategy:
      matrix:
        ubuntu:
          imageName: 'ubuntu-16.04'
    steps:
      - template: ci/check-formatting.yml
    dependsOn: Install

  - job: Test
    strategy:
      matrix:
        ubuntu:
          imageName: 'ubuntu-16.04'
        mac:
          imageName: 'macos-10.13'
        windows:
          imageName: 'vs2017-win2016'
    steps:
      - template: ci/run-tests.yml
    dependsOn: Install
