# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

# pool:
#   vmImage: $(imageName)

jobs:
  - job: Install
    steps:
      - script: |
          $(installCmd)
          echo $(PATH)
        displayName: Install Rust
    strategy:
      matrix:
        ubuntu:
          imageName: 'ubuntu-16.04'
          installCmd:  |
            curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
            echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
        # rhel:
        #   imageName: ''
        #   installCmd: |
        #     curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
        #     echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
        # mac:
        #   imageName: 'macos-10.13'
        #   installCmd: |
        #     curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
        #     echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
        windows:
          imageName: 'vs2017-win2016'
          installCmd: |
            curl -sSf -o rustup-init.exe https://win.rustup.rs
            rustup-init.exe -y --default-toolchain stable
            echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"

  - job: Formatting
    steps:
      - script: rustup component add rustfmt
      - script: cargo fmt --all -q -- --check
    dependsOn: Install

  - job: Test
    steps:
      # the unit tests for all crates (without mocking the network)
      # run single-threaded because some tests change environment variables,
      # which is not thread-safe
      - script: |
          cargo test --all
            --package notion-core \
            --package notion-fail \
            --package archive \
            --package notion-fail-derive \
            --package progress-read \
            -- --test-threads=1
        displayName: 

      # the acceptance tests, using network mocks
      - script: |
          NOTION_DEV=1 RUST_BACKTRACE=full cargo test --features mock-network

      # smoke tests: real data and no mocks
      - script: |
          NOTION_DEV=1 RUST_BACKTRACE=full cargo test \
            --test smoke \
            --features smoke-tests \
            -- --test-threads 1
    displayName: Run Tests
    dependsOn: Install
