# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master
  - refs/tags/*

jobs:
  - job: nix
    strategy:
      matrix:
        ubuntu:
          imageName: "ubuntu-16.04"
        mac:
          imageName: "macos-10.13"
    pool:
      vmImage: $(imageName)
    steps:
      - template: ci/install-rust.yml
      - template: ci/install-bats.yml
      - template: ci/check-formatting.yml
      - template: ci/run-tests.yml
    displayName: Non-Windows OSes

  - job: windows
    strategy:
      matrix:
        windows:
          imageName: "vs2017-win2016"
    pool:
      vmImage: $(imageName)
    steps:
      - template: ci/install-rust.yml
      - template: ci/run-tests.yml
    displayName: Build and Test Windows

  - job: vars
    displayName: Check for build overrides
    steps:
      - bash: ./ci/check-overrides.sh
        name: overrides
        displayName: Extract overrides from top commit

# Note: The following 2 jobscan be removed when the updates feature is complete, along with the file
# 'ci/run-tests-updates.yml' and the check for '[volta updates]' in 'ci/check-overrides.sh'
  - job: nix_test_updates
    dependsOn:
      - vars
      - nix
    strategy:
      matrix:
        ubuntu:
          imageName: "ubuntu-16.04"
        mac:
          imageName: "macos-10.13"
    pool:
      vmImage: $(imageName)
    steps:
      - template: ci/install-rust.yml
      - template: ci/run-tests-updates.yml
    displayName: Test nix (with Updates Feature)
    condition: and(succeeded('nix'), dependencies.vars.outputs['overrides.updates'])

  - job: windows_test_updates
    dependsOn:
      - vars
      - windows
    strategy:
      matrix:
        windows:
          imageName: "vs2017-win2016"
    pool:
      vmImage: $(imageName)
    steps:
      - template: ci/install-rust.yml
      - template: ci/run-tests-updates.yml
    displayName: Test Windows (with Updates Feature)
    condition: and(succeeded('windows'), dependencies.vars.outputs['overrides.updates'])
# End updates special case

  - job: api_docs
    dependsOn:
      - vars
    displayName: Build API Docs
    # Using macOS for this b/c it's substantially the fastest.
    strategy:
      matrix:
        mac:
          imageName: "macos-10.13"
    steps:
      - template: ci/build-api-docs.yml
    condition: or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), dependencies.vars.outputs['overrides.docs'])

  - job: publish_docs
    dependsOn:
      - nix
      - windows
      - api_docs
    displayName: Publish API Docs
    strategy:
      matrix:
        mac:
          imageName: "macos-10.13"
    steps:
      - template: ci/publish-api-docs.yml
    condition: and(succeeded('nix'), succeeded('windows'), succeeded('api_docs'))

  - job: publish_release
    displayName: Publish Release artifacts
    strategy:
      matrix:
        ubuntu:
          imageName: "ubuntu-16.04"
        mac:
          imageName: "macos-10.13"
        windows:
          imageName: "vs2017-win2016"
    steps:
      - template: ci/publish-release.yml
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
