[package]
name = "nemo-cli"
version = "0.1.0"
authors = ["David Herman <david.herman@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/dherman/nemo"

[dependencies]
clap = "2.26.2"
