[package]
name = "notion"
version = "0.1.0"
authors = ["David Herman <david.herman@gmail.com>"]
license = "BSD-2-Clause"
repository = "https://github.com/notion-cli/notion"

[[bin]]
name = "notion"
path = "src/main.rs"

[[bin]]
name = "launchbin"
path = "src/launchbin.rs"

[[bin]]
name = "launchscript"
path = "src/launchscript.rs"

[dependencies]
docopt = "0.8"
notion-core = { path = "crates/notion-core" }
serde = "1.0"
serde_derive = "1.0"
console = "0.6.1"

[workspace]
