[package]
name = "notion"
version = "0.1.3"
authors = ["David Herman <david.herman@gmail.com>"]
license = "BSD-2-Clause"
repository = "https://github.com/notion-cli/notion"

[features]
universal-docs = ["notion-core/universal-docs"]

[[bin]]
name = "notion"
path = "src/notion.rs"

[[bin]]
name = "node"
path = "src/node.rs"

[[bin]]
name = "yarn"
path = "src/yarn.rs"

[[bin]]
name = "launchbin"
path = "src/launchbin.rs"

[[bin]]
name = "launchscript"
path = "src/launchscript.rs"

[dependencies]
docopt = "0.8"
notion-core = { path = "crates/notion-core" }
serde = "1.0"
serde_derive = "1.0"
console = "0.6.1"
failure_derive = "0.1.1"
failure = "0.1.1"
notion-fail = { path = "crates/notion-fail" }
notion-fail-derive = { path = "crates/notion-fail-derive" }
semver = "0.9.0"
result = "1.0.0"

[workspace]
