[package]
name = "nodeup"
version = "0.1.0"
authors = ["David Herman <david.herman@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/dherman/nodeup"

[[bin]]
name = "nodeup"
path = "src/main.rs"

[[bin]]
name = "launchbin"
path = "src/launchbin.rs"

[[bin]]
name = "launchscript"
path = "src/launchscript.rs"

[dependencies]
clap = "2.26.2"
nodeup-core = { path = "crates/nodeup-core" }

[workspace]
