[package]
name = "nodeup"
version = "0.1.0"
authors = ["David Herman <david.herman@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/dherman/nodeup"

[[bin]]
name = "nodeup"
path = "src/main.rs"

[[bin]]
name = "binstub"
path = "src/binstub.rs"

[[bin]]
name = "scriptstub"
path = "src/scriptstub.rs"

[dependencies]
clap = "2.26.2"
nodeup-core = { path = "crates/nodeup-core" }

[workspace]
