[package]
name = "volta-logging"
version = "0.1.0"
authors = ["Chuck Pierce <cpierce.grad@gmail.com>"]
edition = "2018"

[dependencies]
atty = "0.2"
console = "0.6.1"
log = { version = "0.4", features = ["std"] }
term_size = "0.3.0"
textwrap = "0.11.0"
