[package]
name = "volta-migrate"
version = "0.1.0"
authors = ["Charles Pierce <cpierce.grad@gmail.com>"]
edition = "2018"

[dependencies]
volta-core = { path = "../volta-core" }
volta-fail = { path = "../volta-fail" }
volta-layout = { path = "../volta-layout" }
log = { version = "0.4", features = ["std"] }
tempfile = "3.0.2"
semver = { git = "https://github.com/mikrostew/semver", branch = "new-parser" }
