[package]
name = "notion-fail"
version = "0.1.0"
authors = ["Dave Herman <david.herman@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1.1"
failure_derive = "0.1.1"
notion-fail-derive = { path = "../notion-fail-derive" }
serde = { version = "1.0.85", features = ["derive"] }
