[package]
name = "guid"
version = "0.1.0"
description = "A convenient macro for creating Windows GUIDs."
authors = ["David Herman <david.herman@gmail.com>"]

[dependencies]

[target.'cfg(windows)'.dependencies]
winapi = "0.2.8"
