on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Test Package Feature

jobs:
  tests:
    strategy:
      matrix:
        os:
          - ubuntu
          - macos
          - windows
    name: Acceptance Tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}-latest
    env:
      RUST_BACKTRACE: full
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up cargo
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --features mock-network,package-global
      - name: Lint with clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --features package-global
      - name: Lint tests with clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --tests --features mock-network,package-global

  smoke-tests:
    name: Smoke Tests
    runs-on: macos-latest
    env:
      RUST_BACKTRACE: full
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up cargo
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --test smoke --features smoke-tests,package-global -- --test-threads 1
